name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      solution:
        description: 'Build Solution'
        required: true
        default: 'Release'
        type: string
      artifact:
        description: 'Upload to Artifact'
        required: false
        default: true
        type: boolean
      release:
        description: 'Generate a new Release'
        required: false
        default: false
        type: boolean
      pre_release:
        description: 'Generate a new Pre Release'
        required: false
        default: false
        type: boolean
      overwrite_release:
        description: 'Overwrite Existing Release'
        required: false
        default: true
        type: boolean
      rel_title:
        description: 'Release Description Title'     
        required: false
        default: 'v1.9.50a'
        type: string
      rel_tag:
        description: 'Release Tag'     
        required: false
        default: 'v1.9.50a'
        type: string
      rel_desc_body:
        description: 'Release Description Body'     
        required: false
        default: 'Adapt to BDS version: '
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build Project
        env: 
          SOLUTION: ${{ inputs.solution.default }}
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild.exe /m /p:Configuration=$SOLUTION ./
        shell: bash

      - name: Organize dll and pdb files
        env: 
          SOLUTION: ${{ inputs.solution.default }}
        run: |
          mkdir ./release/
          mkdir ./release/zip/
          cp ./x64/${SOLUTION}/BDSpyrunner.dll ./release/
          cp ./x64/${SOLUTION}/BDSpyrunner.pdb ./release/
          cp ./pyTools/mc.py ./release/
          cp ./pyTools/test.py ./release/
          cp ./pyTools/symchk.py ./release/
        shell: bash

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: all.zip
          path: ./release/
          directory: ./release/

      - name: Upload build files
        uses: actions/upload-artifact@v2
        if: inputs.artifact
        with:
          name: build
          path: ./x64/dllpdb
          
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        if: inputs.release
        with:
          tag: ${{ inputs.rel_tag }}
          release_name: ${{ inputs.rel_title }}
          overwrite: ${{ inputs.overwrite_release.default }}
          prerelease: ${{ inputs.pre_release.default }}
          body: ${{ inputs.rel_desc_body }}
          files: |
            ./release/BDSpyrunner.dll
            ./release/BDSpyrunner.pdb
            ./release/mc.py
            ./release/test.py
            ./release/symchk.py
            ./release/all.zip
