name: Build

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64

      - name: Build Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Debug -j

      - name: Organize dll and pdb files
        run: |
          mkdir ./build/dllpdb
          cp ./build/Debug/BDSpyrunnerW.dll ./build/dllpdb
          cp ./build/Debug/BDSpyrunnerW.pdb ./build/dllpdb
          
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/dllpdb