name: Build

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Debug ./

      - name: Organize dll and pdb files
        run: |
          mkdir ./x64/dllpdb
          cp ./x64/Debug/BDSpyrunnerW.dll ./x64/dllpdb
          cp ./x64/Debug/BDSpyrunnerW.pdb ./x64/dllpdb
          
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./x64/dllpdb