
on:
  push:
    tags:
      - 'v*' # such as v1.6.2

env:
  SOLUTION_FILE_PATH: .
  Platform: X64
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.7
        whth:
          files: |
            ./out/BDSpyrunner.dll
            ./out/BDSpyrunner.pdb