name: Release

on:
  workflow_dispatch:
    inputs:
      solution:
        description: 'Build Solution'
        required: true
        default: 'Release'
        type: string
      artifact:
        description: 'Upload to Artifact'
        required: false
        default: true
        type: boolean
      release:
        description: 'Generate a new Release'
        required: false
        default: true
        type: boolean
      pre_release:
        description: 'Generate a new Pre Release'
        required: false
        default: false
        type: boolean
      rel_title:
        description: 'Release Description Title'     
        required: false
        default: 'v1.19.52a'
        type: string
      rel_tag:
        description: 'Release Tag'     
        required: false
        default: 'v1.19.52a'
        type: string
      rel_desc_body:
        description: 'Release Description Body'     
        required: false
        default: 'Adapt to BDS version: '
        type: string

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64
            
      - name: Build Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config ${{ inputs.solution }} -j

      - name: Organize dll and pdb files
        run: |
          mkdir ./release/
          mkdir ./build/dllpdb/
          cp ./build/${{ inputs.solution }}/BDSpyrunnerW.dll ./build/dllpdb/
          cp ./build/${{ inputs.solution }}/BDSpyrunnerW.pdb ./build/dllpdb/
          cp ./build/${{ inputs.solution }}/BDSpyrunnerW.dll ./release/
          cp ./build/${{ inputs.solution }}/BDSpyrunnerW.pdb ./release/
          curl -fsSL "https://pyr.jfishing.love/plugins/mc.py" -o ./release/mc.py
          cp ./tools/test.py ./release/
          cp ./tools/symchk.py ./release/
          ls ./build/dllpdb/
          ls ./release/

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: all.zip
          path: .
          directory: release

      - name: Upload build files
        uses: actions/upload-artifact@v2
        if: inputs.artifact
        with:
          name: build
          path: ./build/dllpdb
          
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: inputs.release
        with:
          tag_name: ${{ inputs.rel_tag }}
          name: ${{ inputs.rel_title }}
          prerelease: ${{ inputs.pre_release }}
          body: ${{ inputs.rel_desc_body }}
          files: |
            ./release/BDSpyrunnerW.dll
            ./release/BDSpyrunnerW.pdb
            ./release/mc.py
            ./release/test.py
            ./release/symchk.py
            ./release/all.zip