name: Build and Release

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Release ./

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            ./x64/Release/BDSpyrunner.dll
            ./x64/Release/BDSpyrunner.pdb
            ./mc.py
